#!/usr/bin/env bash
# PreToolUse(Edit|Write|NotebookEdit) guardrail: refuse hand-edits to files that
# are produced by a generator. Editing them "works" until the generator runs
# again and silently reverts the change -- the classic R-package wrong turn.
set -uo pipefail

payload="$(cat)"
f="$(printf '%s' "$payload" | jq -r '.tool_input.file_path // .tool_input.notebook_path // empty' 2>/dev/null)"
[ -z "$f" ] && exit 0

deny() {
  jq -n --arg r "$1" '{hookSpecificOutput: {
    hookEventName: "PreToolUse",
    permissionDecision: "deny",
    permissionDecisionReason: $r}}'
  exit 0
}

base="$(basename "$f")"

case "$f" in
  */man/*.Rd|man/*.Rd)
    deny "BLOCKED: man/${base} is generated by roxygen2. Edit the roxygen block above the function in R/ and run 'Rscript -e \"devtools::document()\"'. A hand-edit here is erased on the next document() run." ;;
  */NAMESPACE|NAMESPACE)
    deny "BLOCKED: NAMESPACE is generated by roxygen2. Add/adjust @export, @importFrom or @rawNamespace tags in R/ and run 'Rscript -e \"devtools::document()\"'." ;;
  */renv.lock|renv.lock)
    deny "BLOCKED: renv.lock is a generated manifest. Install/remove the package first, then run 'renv::snapshot()' so the lockfile matches a library that actually resolves. Hand-edited lockfiles fail on the next restore." ;;
  */renv/activate.R|renv/activate.R)
    deny "BLOCKED: renv/activate.R is written by renv. Run 'renv::upgrade()' or 'renv::activate()' instead." ;;
  */_targets/meta/*|_targets/meta/*)
    deny "BLOCKED: _targets/meta/ is the {targets} store bookkeeping. Editing it corrupts target provenance. To force a rebuild use 'targets::tar_invalidate(<name>)' or 'targets::tar_destroy()'." ;;
esac

case "$base" in
  README.md)
    # Only guarded when a README source file sits beside it.
    d="$(dirname "$f")"
    for src in README.Rmd README.qmd; do
      if [ -f "$d/$src" ]; then
        deny "BLOCKED: ${base} is knitted from ${src}. Edit $d/${src}, then re-render it. Editing the .md directly is lost on the next render."
      fi
    done ;;
  *.html)
    d="$(dirname "$f")"; stem="${base%.html}"
    for src in "$stem.qmd" "$stem.Rmd"; do
      [ -f "$d/$src" ] && deny "BLOCKED: ${base} is rendered output from ${src}. Edit $d/${src} and re-render."
    done ;;
esac

exit 0
